import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LANG_KEY = "sugarhive_language";

const translations: Record<string, Record<Language, string>> = {
  "nav.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "nav.checklists": { en: "Checklists", ar: "قوائم المهام" },
  "nav.management": { en: "Management", ar: "الإدارة" },
  "nav.branches": { en: "Branches", ar: "الفروع" },
  "nav.team": { en: "Team", ar: "الفريق" },
  "nav.training": { en: "Training", ar: "التدريب" },
  "nav.signOut": { en: "Sign Out", ar: "تسجيل الخروج" },
  "nav.settings": { en: "Settings", ar: "الإعدادات" },
  "nav.reports": { en: "Reports", ar: "التقارير" },

  "role.admin": { en: "Admin", ar: "مدير النظام" },
  "role.manager": { en: "Manager", ar: "مدير" },
  "role.supervisor": { en: "Supervisor", ar: "مشرف" },
  "role.employee": { en: "Employee", ar: "موظف" },
  "role.superAdmin": { en: "Super Admin", ar: "المدير العام" },
  "role.branchManager": { en: "Branch Manager", ar: "مدير الفرع" },
  "role.operations": { en: "Operations", ar: "العمليات" },

  "header.search": { en: "Search...", ar: "بحث..." },

  "home.title": { en: "Dashboard", ar: "لوحة التحكم" },
  "home.welcome": { en: "Welcome back", ar: "مرحبًا بعودتك" },
  "home.totalBranches": { en: "Total Branches", ar: "إجمالي الفروع" },
  "home.activeChecklists": { en: "Active Checklists", ar: "قوائم المهام النشطة" },
  "home.teamMembers": { en: "Team Members", ar: "أعضاء الفريق" },
  "home.trainingCourses": { en: "Training Courses", ar: "دورات التدريب" },
  "home.recentActivity": { en: "Recent Activity", ar: "النشاط الأخير" },
  "home.quickActions": { en: "Quick Actions", ar: "إجراءات سريعة" },
  "home.newChecklist": { en: "New Checklist", ar: "قائمة مهام جديدة" },
  "home.addMember": { en: "Add Member", ar: "إضافة عضو" },
  "home.viewReports": { en: "View Reports", ar: "عرض التقارير" },
  "home.dailyReport": { en: "Daily Report", ar: "التقرير اليومي" },
  "home.branchReport": { en: "Branch Report", ar: "تقرير الفروع" },
  "home.overview": { en: "Overview", ar: "نظرة عامة" },
  "home.completedCourses": { en: "Completed Courses", ar: "الدورات المكتملة" },
  "home.inProgressCourses": { en: "In Progress Courses", ar: "الدورات الجارية" },
  "home.upcomingTasks": { en: "Upcoming Tasks", ar: "المهام القادمة" },
  "home.noActivity": { en: "No recent activity", ar: "لا يوجد نشاط حديث" },
  "home.viewAll": { en: "View All", ar: "عرض الكل" },
  "home.checklistProgress": { en: "Checklist Progress", ar: "تقدم قوائم المهام" },
  "home.trainingProgress": { en: "Training Progress", ar: "تقدم التدريب" },
  "home.performance": { en: "Performance", ar: "الأداء" },
  "home.operationsDashboard": { en: "Operations Dashboard", ar: "لوحة العمليات" },
  "home.subtitle": { en: "Here's what's happening across SugarHive today.", ar: "إليك ما يحدث في SugarHive اليوم." },
  "home.completedTasks": { en: "Completed Tasks", ar: "المهام المكتملة" },
  "home.pendingTasks": { en: "Pending Tasks", ar: "المهام المعلقة" },
  "home.activeUsers": { en: "Active Users", ar: "المستخدمون النشطون" },
  "home.overdueTasks": { en: "Overdue Tasks", ar: "المهام المتأخرة" },
  "home.liveOperations": { en: "Live Operations", ar: "العمليات المباشرة" },
  "home.liveOperationsDesc": { en: "Real-time checklist execution status", ar: "حالة تنفيذ قوائم المهام في الوقت الفعلي" },
  "home.viewAllOperations": { en: "View All Operations", ar: "عرض جميع العمليات" },
  "home.trainingHub": { en: "Training Hub", ar: "مركز التدريب" },
  "home.trainingHubDesc": { en: "Skill development metrics", ar: "مقاييس تطوير المهارات" },
  "home.noCompletedCourses": { en: "No completed courses yet.", ar: "لا توجد دورات مكتملة بعد." },
  "home.certifiedToday": { en: "Certified Today", ar: "معتمدون اليوم" },
  "home.manage": { en: "Manage", ar: "إدارة" },
  "home.operationalLogs": { en: "Operational Logs", ar: "سجلات العمليات" },
  "home.exportCSV": { en: "Export as CSV", ar: "تصدير كـ CSV" },
  "home.noLogs": { en: "No operational logs yet. Activity will appear here as your team works.", ar: "لا توجد سجلات عمليات بعد. سيظهر النشاط هنا مع عمل فريقك." },
  "home.taskAssigned": { en: "Task Assigned", ar: "تم تعيين المهمة" },
  "home.taskAssignedDesc": { en: "The task has been successfully assigned to the team member.", ar: "تم تعيين المهمة بنجاح لعضو الفريق." },
  "home.noLogs.export": { en: "No Logs", ar: "لا توجد سجلات" },
  "home.noLogsExportDesc": { en: "There are no operational logs to export.", ar: "لا توجد سجلات عمليات للتصدير." },
  "home.logsExported": { en: "Logs Exported", ar: "تم تصدير السجلات" },

  "checklists.title": { en: "Checklists", ar: "قوائم المهام" },
  "checklists.all": { en: "All", ar: "الكل" },
  "checklists.active": { en: "Active", ar: "نشط" },
  "checklists.completed": { en: "Completed", ar: "مكتمل" },
  "checklists.overdue": { en: "Overdue", ar: "متأخر" },
  "checklists.drafts": { en: "Drafts", ar: "مسودات" },
  "checklists.newChecklist": { en: "New Checklist", ar: "قائمة مهام جديدة" },
  "checklists.noChecklists": { en: "No checklists found", ar: "لا توجد قوائم مهام" },
  "checklists.completion": { en: "Completion", ar: "الإنجاز" },
  "checklists.history": { en: "History", ar: "السجل" },
  "checklists.editTemplate": { en: "Edit Template", ar: "تعديل القالب" },
  "checklists.duplicate": { en: "Duplicate", ar: "نسخ" },
  "checklists.export": { en: "Export", ar: "تصدير" },
  "checklists.delete": { en: "Delete", ar: "حذف" },
  "checklists.templateActions": { en: "Template Actions", ar: "إجراءات القالب" },
  "checklists.createNew": { en: "Create New Checklist", ar: "إنشاء قائمة مهام جديدة" },
  "checklists.title_field": { en: "Title", ar: "العنوان" },
  "checklists.frequency": { en: "Frequency", ar: "التكرار" },
  "checklists.startDate": { en: "Start Date", ar: "تاريخ البدء" },
  "checklists.endDate": { en: "End Date", ar: "تاريخ الانتهاء" },
  "checklists.startTime": { en: "Start Time", ar: "وقت البدء" },
  "checklists.endTime": { en: "End Time", ar: "وقت الانتهاء" },
  "checklists.branches": { en: "Branches", ar: "الفروع" },
  "checklists.assignees": { en: "Assignees", ar: "المكلفون" },
  "checklists.saveDraft": { en: "Save as Draft", ar: "حفظ كمسودة" },
  "checklists.publish": { en: "Publish", ar: "نشر" },
  "checklists.cancel": { en: "Cancel", ar: "إلغاء" },
  "checklists.noHistory": { en: "No history yet. History is saved when a checklist is completed or reset.", ar: "لا يوجد سجل بعد. يتم حفظ السجل عند اكتمال قائمة المهام أو إعادة تعيينها." },
  "checklists.management": { en: "Checklists Management", ar: "إدارة قوائم المهام" },
  "checklists.manageTrack": { en: "Manage and track daily operational tasks", ar: "إدارة وتتبع المهام التشغيلية اليومية" },
  "checklists.pending": { en: "Pending", ar: "قيد الانتظار" },
  "checklists.filter": { en: "Filter", ar: "تصفية" },
  "checklists.filterByFrequency": { en: "Filter by Frequency", ar: "تصفية حسب التكرار" },
  "checklists.searchChecklists": { en: "Search checklists...", ar: "البحث في قوائم المهام..." },
  "checklists.showing": { en: "Showing", ar: "عرض" },
  "checklists.checklistsCount": { en: "checklists", ar: "قوائم مهام" },
  "checklists.previous": { en: "Previous", ar: "السابق" },
  "checklists.next": { en: "Next", ar: "التالي" },
  "checklists.checklistTitle": { en: "Checklist Title", ar: "عنوان قائمة المهام" },
  "checklists.selectFrequency": { en: "Select frequency", ar: "اختر التكرار" },
  "checklists.selectStartTime": { en: "Select start time", ar: "اختر وقت البدء" },
  "checklists.selectEndTime": { en: "Select end time", ar: "اختر وقت الانتهاء" },
  "checklists.targetBranches": { en: "Target Branches", ar: "الفروع المستهدفة" },
  "checklists.selectBranches": { en: "Select branches", ar: "اختر الفروع" },
  "checklists.allBranches": { en: "All Branches", ar: "جميع الفروع" },
  "checklists.assignToSupervisors": { en: "Assign to Supervisors", ar: "تعيين للمشرفين" },
  "checklists.selectSupervisors": { en: "Select supervisors", ar: "اختر المشرفين" },
  "checklists.selectBranchesFirst": { en: "Select branches first", ar: "اختر الفروع أولاً" },
  "checklists.updateTemplate": { en: "Update Template", ar: "تحديث القالب" },
  "checklists.nextAddTasks": { en: "Next: Add Tasks", ar: "التالي: إضافة مهام" },
  "checklists.editChecklistTemplate": { en: "Edit Checklist Template", ar: "تعديل قالب قائمة المهام" },
  "checklists.newChecklistTemplate": { en: "New Checklist Template", ar: "قالب قائمة مهام جديد" },
  "checklists.editDescription": { en: "Update the operational procedures for this template.", ar: "تحديث الإجراءات التشغيلية لهذا القالب." },
  "checklists.newDescription": { en: "Define a new set of operational procedures.", ar: "تحديد مجموعة جديدة من الإجراءات التشغيلية." },
  "checklists.deleteTemplate": { en: "Delete Template", ar: "حذف القالب" },
  "checklists.deleteConfirmMessage": { en: "Are you sure you want to delete this template? This action cannot be undone.", ar: "هل أنت متأكد من حذف هذا القالب؟ لا يمكن التراجع عن هذا الإجراء." },
  "checklists.viewHistory": { en: "View History", ar: "عرض السجل" },
  "checklists.exportPDF": { en: "Export PDF", ar: "تصدير PDF" },
  "checklists.ongoing": { en: "Ongoing", ar: "مستمر" },
  "checklists.endDateAfterStart": { en: "End date must be on or after start date", ar: "يجب أن يكون تاريخ الانتهاء بعد تاريخ البدء" },
  "checklists.endTimeAfterStart": { en: "End time must be after start time", ar: "يجب أن يكون وقت الانتهاء بعد وقت البدء" },
  "checklists.done": { en: "done", ar: "مكتمل" },
  "checklists.partialCount": { en: "partial", ar: "جزئي" },
  "checklists.missed": { en: "missed", ar: "فائت" },
  "checklists.completedBy": { en: "Completed by:", ar: "أكمله:" },
  "checklists.templateUpdated": { en: "Template Updated", ar: "تم تحديث القالب" },
  "checklists.templateUpdatedDesc": { en: "Your checklist template has been updated successfully.", ar: "تم تحديث قالب قائمة المهام بنجاح." },
  "checklists.draftCreated": { en: "Draft Created", ar: "تم إنشاء المسودة" },
  "checklists.draftCreatedDesc": { en: "Now add tasks to your checklist, then click Publish.", ar: "أضف المهام الآن إلى قائمة المهام، ثم انقر على نشر." },
  "checklists.templateDuplicated": { en: "Template Duplicated", ar: "تم نسخ القالب" },
  "checklists.templateDuplicatedDesc": { en: "A copy of the template has been created.", ar: "تم إنشاء نسخة من القالب." },
  "checklists.templateDeleted": { en: "Template Deleted", ar: "تم حذف القالب" },
  "checklists.templateDeletedDesc": { en: "The checklist template has been removed.", ar: "تم إزالة قالب قائمة المهام." },
  "checklists.exportingPDF": { en: "Exporting PDF", ar: "جاري تصدير PDF" },
  "checklists.exportingPDFDesc": { en: "Generating operational report for", ar: "جاري إنشاء التقرير التشغيلي لـ" },
  "checklists.exportComplete": { en: "Export Complete", ar: "اكتمل التصدير" },
  "checklists.exportCompleteDesc": { en: "PDF report has been downloaded.", ar: "تم تحميل تقرير PDF." },

  "checklist.tasks": { en: "Tasks", ar: "المهام" },
  "checklist.addTask": { en: "Add Task", ar: "إضافة مهمة" },
  "checklist.addTasks": { en: "Add Tasks", ar: "إضافة مهام" },
  "checklist.complete": { en: "Complete", ar: "مكتمل" },
  "checklist.partial": { en: "Partial", ar: "جزئي" },
  "checklist.incomplete": { en: "Incomplete", ar: "غير مكتمل" },
  "checklist.completeAll": { en: "Complete All", ar: "إكمال الكل" },
  "checklist.resetAll": { en: "Reset All", ar: "إعادة تعيين الكل" },
  "checklist.unpublish": { en: "Unpublish", ar: "إلغاء النشر" },
  "checklist.back": { en: "Back to Checklists", ar: "العودة لقوائم المهام" },
  "checklist.progress": { en: "Progress", ar: "التقدم" },
  "checklist.status": { en: "Status", ar: "الحالة" },
  "checklist.assignedTo": { en: "Assigned To", ar: "مكلف إلى" },
  "checklist.dueDate": { en: "Due Date", ar: "تاريخ الاستحقاق" },
  "checklist.comment": { en: "Comment", ar: "تعليق" },
  "checklist.addComment": { en: "Add comment...", ar: "أضف تعليقًا..." },
  "checklist.photo": { en: "Photo", ar: "صورة" },
  "checklist.deleteTask": { en: "Delete Task", ar: "حذف المهمة" },
  "checklist.editTask": { en: "Edit Task", ar: "تعديل المهمة" },
  "checklist.details": { en: "Checklist Details", ar: "تفاصيل قائمة المهام" },
  "checklist.publishChecklist": { en: "Publish Checklist", ar: "نشر قائمة المهام" },
  "checklist.draftMode": { en: "Draft Mode", ar: "وضع المسودة" },
  "checklist.draftModeDesc": { en: "Add tasks below, then click \"Publish Checklist\" to make it live and notify assignees.", ar: "أضف المهام أدناه، ثم انقر على \"نشر قائمة المهام\" لجعلها مباشرة وإخطار المكلفين." },
  "checklist.scheduledChecklist": { en: "Scheduled Checklist", ar: "قائمة مهام مجدولة" },
  "checklist.editChecklist": { en: "Edit Checklist", ar: "تعديل قائمة المهام" },
  "checklist.checklistTitle": { en: "Checklist Title", ar: "عنوان قائمة المهام" },
  "checklist.deleteChecklist": { en: "Delete Checklist", ar: "حذف قائمة المهام" },
  "checklist.unpublishChecklist": { en: "Unpublish Checklist", ar: "إلغاء نشر قائمة المهام" },
  "checklist.unpublishMessage": { en: "Are you sure you want to unpublish this checklist? It will be moved back to draft mode and hidden from the checklist list until published again.", ar: "هل أنت متأكد من إلغاء نشر قائمة المهام؟ سيتم نقلها إلى وضع المسودة وإخفاؤها حتى يتم نشرها مرة أخرى." },
  "checklist.noTasksYet": { en: "No tasks yet", ar: "لا توجد مهام بعد" },
  "checklist.addTasksToChecklist": { en: "Add tasks to this checklist.", ar: "أضف مهامًا إلى قائمة المهام هذه." },
  "checklist.noTasksAssigned": { en: "No tasks have been assigned yet.", ar: "لم يتم تعيين مهام بعد." },
  "checklist.operationalTasks": { en: "Operational Tasks", ar: "المهام التشغيلية" },
  "checklist.reviewTasks": { en: "Review the tasks in this checklist.", ar: "راجع المهام في قائمة المهام هذه." },
  "checklist.setStatusTasks": { en: "Set the status for each task below.", ar: "حدد الحالة لكل مهمة أدناه." },
  "checklist.viewTasks": { en: "View the tasks in this checklist.", ar: "عرض المهام في قائمة المهام هذه." },
  "checklist.onlySupervisors": { en: "Only supervisors can update task status", ar: "فقط المشرفون يمكنهم تحديث حالة المهمة" },
  "checklist.changePhoto": { en: "Change Photo", ar: "تغيير الصورة" },
  "checklist.takePhoto": { en: "Take Photo", ar: "التقاط صورة" },
  "checklist.photoConfirm": { en: "Please take a photo to confirm completion", ar: "يرجى التقاط صورة لتأكيد الإنجاز" },
  "checklist.commentWhy": { en: "Add a comment explaining why...", ar: "أضف تعليقًا يوضح السبب..." },
  "checklist.commentRequired": { en: "Please add a comment explaining why", ar: "يرجى إضافة تعليق يوضح السبب" },
  "checklist.completionProgress": { en: "Completion Progress", ar: "تقدم الإنجاز" },
  "checklist.target": { en: "Target: 100%", ar: "الهدف: 100%" },
  "checklist.frequency": { en: "Frequency", ar: "التكرار" },
  "checklist.assignee": { en: "Assignee", ar: "المكلف" },
  "checklist.timeWindow": { en: "Time Window", ar: "الإطار الزمني" },
  "checklist.overdueMessage": { en: "Past deadline - this checklist is overdue", ar: "تجاوز الموعد النهائي - قائمة المهام متأخرة" },
  "checklist.operationHistory": { en: "Operation History", ar: "سجل العمليات" },
  "checklist.noHistoryYet": { en: "No history recorded yet", ar: "لم يتم تسجيل أي سجل بعد" },
  "checklist.completedBy": { en: "by", ar: "بواسطة" },
  "checklist.itemsCompleted": { en: "items completed", ar: "عناصر مكتملة" },
  "checklist.itemsPartial": { en: "partial", ar: "جزئي" },
  "checklist.itemsIncomplete": { en: "incomplete", ar: "غير مكتمل" },
  "checklist.loadingDetails": { en: "Loading checklist details...", ar: "جار تحميل تفاصيل قائمة المهام..." },
  "checklist.completedToast": { en: "Checklist Completed", ar: "اكتملت قائمة المهام" },
  "checklist.completedDesc": { en: "All tasks have been marked as finished. Saved to history.", ar: "تم تحديد جميع المهام كمنتهية. تم الحفظ في السجل." },
  "checklist.notAvailableYet": { en: "Not Available Yet", ar: "غير متاح بعد" },
  "checklist.tasksAdded": { en: "Tasks Added", ar: "تمت إضافة المهام" },
  "checklist.taskDeleted": { en: "Task Deleted", ar: "تم حذف المهمة" },
  "checklist.taskDeletedDesc": { en: "The task has been removed from this checklist.", ar: "تمت إزالة المهمة من قائمة المهام هذه." },
  "checklist.taskUpdated": { en: "Task Updated", ar: "تم تحديث المهمة" },
  "checklist.taskUpdatedDesc": { en: "The task has been updated.", ar: "تم تحديث المهمة." },
  "checklist.checklistUpdated": { en: "Checklist Updated", ar: "تم تحديث قائمة المهام" },
  "checklist.checklistUpdatedDesc": { en: "The checklist title has been updated.", ar: "تم تحديث عنوان قائمة المهام." },
  "checklist.cannotPublish": { en: "Cannot Publish", ar: "لا يمكن النشر" },
  "checklist.addTaskFirst": { en: "Add at least one task before publishing.", ar: "أضف مهمة واحدة على الأقل قبل النشر." },
  "checklist.published": { en: "Checklist Published", ar: "تم نشر قائمة المهام" },
  "checklist.publishedDesc": { en: "The checklist is now live and assignees have been notified.", ar: "قائمة المهام مباشرة الآن وتم إخطار المكلفين." },
  "checklist.unpublished": { en: "Checklist Unpublished", ar: "تم إلغاء نشر قائمة المهام" },
  "checklist.unpublishedDesc": { en: "The checklist has been moved back to draft mode.", ar: "تم نقل قائمة المهام إلى وضع المسودة." },
  "checklist.deleted": { en: "Checklist Deleted", ar: "تم حذف قائمة المهام" },
  "checklist.deletedDesc": { en: "The checklist has been removed.", ar: "تمت إزالة قائمة المهام." },
  "checklist.addTasksTo": { en: "Add Tasks to", ar: "إضافة مهام إلى" },
  "checklist.createTasksDesc": { en: "Create the tasks for this checklist. You can type your own or pick from suggestions.", ar: "أنشئ مهام قائمة المهام هذه. يمكنك كتابة مهامك أو الاختيار من الاقتراحات." },
  "checklist.newTask": { en: "New Task", ar: "مهمة جديدة" },
  "checklist.typeTask": { en: "Type a task and press Enter...", ar: "اكتب مهمة واضغط Enter..." },
  "checklist.add": { en: "Add", ar: "إضافة" },
  "checklist.suggestedTasks": { en: "Suggested Tasks", ar: "مهام مقترحة" },
  "checklist.addedTasks": { en: "Added Tasks", ar: "المهام المضافة" },
  "checklist.saveTasks": { en: "Save Tasks", ar: "حفظ المهام" },

  "training.title": { en: "Training", ar: "التدريب" },
  "training.allCourses": { en: "All Courses", ar: "جميع الدورات" },
  "training.myAssignedCourses": { en: "My Assigned Courses", ar: "دوراتي المعينة" },
  "training.newCourse": { en: "New Course", ar: "دورة جديدة" },
  "training.createCourse": { en: "Create Course", ar: "إنشاء دورة" },
  "training.editCourse": { en: "Edit Course", ar: "تعديل الدورة" },
  "training.startCourse": { en: "Start Course", ar: "بدء الدورة" },
  "training.continueCourse": { en: "Continue Course", ar: "متابعة الدورة" },
  "training.continueLearning": { en: "Continue Learning", ar: "متابعة التعلم" },
  "training.courseCompleted": { en: "Course Completed!", ar: "اكتملت الدورة!" },
  "training.lessonCompleted": { en: "Lesson Completed", ar: "اكتمل الدرس" },
  "training.nextLesson": { en: "Next Lesson", ar: "الدرس التالي" },
  "training.previousLesson": { en: "Previous", ar: "السابق" },
  "training.backToCourses": { en: "Back to Courses", ar: "العودة للدورات" },
  "training.aboutCourse": { en: "About this course", ar: "عن هذه الدورة" },
  "training.whatYoullLearn": { en: "What you'll learn", ar: "ما ستتعلمه" },
  "training.courseMaterials": { en: "Course Materials", ar: "مواد الدورة" },
  "training.myProgress": { en: "My Progress", ar: "تقدمي" },
  "training.assignedEmployeesProgress": { en: "Assigned Employees Progress", ar: "تقدم الموظفين المعينين" },
  "training.employeeProgress": { en: "Employee Progress", ar: "تقدم الموظفين" },
  "training.yourTrainingProgress": { en: "Your training progress", ar: "تقدمك في التدريب" },
  "training.trainingProgressByEmployee": { en: "Training progress by employee", ar: "تقدم التدريب حسب الموظف" },
  "training.noEmployeesAssigned": { en: "No employees assigned to courses yet.", ar: "لا يوجد موظفين معينين للدورات بعد." },
  "training.certifications": { en: "Certifications", ar: "الشهادات" },
  "training.activeCourses": { en: "Active Courses", ar: "الدورات النشطة" },
  "training.totalCourses": { en: "Total Courses", ar: "إجمالي الدورات" },
  "training.enrolled": { en: "Enrolled", ar: "المسجلين" },
  "training.duration": { en: "Duration", ar: "المدة" },
  "training.lessons": { en: "Lessons", ar: "الدروس" },
  "training.modules": { en: "Modules", ar: "الوحدات" },
  "training.instructor": { en: "Instructor", ar: "المدرب" },
  "training.completed": { en: "Completed", ar: "مكتمل" },
  "training.inProgress": { en: "In Progress", ar: "قيد التنفيذ" },
  "training.notStarted": { en: "Not Started", ar: "لم يبدأ" },
  "training.courseTitle": { en: "Course Title", ar: "عنوان الدورة" },
  "training.description": { en: "Description", ar: "الوصف" },
  "training.category": { en: "Category", ar: "الفئة" },
  "training.assignTo": { en: "Assign To", ar: "تعيين إلى" },
  "training.save": { en: "Save", ar: "حفظ" },
  "training.saveCourse": { en: "Save Course", ar: "حفظ الدورة" },
  "training.lesson": { en: "Lesson", ar: "درس" },
  "training.trainingAndDevelopment": { en: "Training & Development", ar: "التدريب والتطوير" },
  "training.trainingHub": { en: "Training Hub", ar: "مركز التدريب" },
  "training.developSkills": { en: "Develop skills and track employee progress", ar: "تطوير المهارات وتتبع تقدم الموظفين" },
  "training.newTrainingCourse": { en: "New Training Course", ar: "دورة تدريبية جديدة" },
  "training.createModuleDesc": { en: "Create a new educational module for your team.", ar: "أنشئ وحدة تعليمية جديدة لفريقك." },
  "training.courseThumbnail": { en: "Course Thumbnail", ar: "صورة الدورة" },
  "training.changeImage": { en: "Change Image", ar: "تغيير الصورة" },
  "training.clickUploadImage": { en: "Click to upload course image", ar: "اضغط لرفع صورة الدورة" },
  "training.instructorEmail": { en: "Instructor Email", ar: "بريد المدرب" },
  "training.addNewCategory": { en: "Add new category...", ar: "إضافة فئة جديدة..." },
  "training.add": { en: "Add", ar: "إضافة" },
  "training.selectTeamMembers": { en: "Select team members...", ar: "اختر أعضاء الفريق..." },
  "training.selectAll": { en: "Select All", ar: "تحديد الكل" },
  "training.enterLessonTitle": { en: "Enter lesson title...", ar: "أدخل عنوان الدرس..." },
  "training.required": { en: "Required:", ar: "مطلوب:" },
  "training.uploadVideo": { en: "Upload Video", ar: "رفع فيديو" },
  "training.uploadPdf": { en: "Upload PDF", ar: "رفع PDF" },
  "training.uploadPowerPoint": { en: "Upload PowerPoint", ar: "رفع PowerPoint" },
  "training.noLessonsYet": { en: "No lessons added yet. Each lesson requires a video, PDF, or PowerPoint attachment.", ar: "لم تتم إضافة دروس بعد. كل درس يتطلب فيديو أو PDF أو PowerPoint مرفق." },
  "training.publishCourse": { en: "Publish Course", ar: "نشر الدورة" },
  "training.activeLearners": { en: "Active Learners", ar: "المتعلمون النشطون" },
  "training.assignToEmployees": { en: "Assign To (Employees)", ar: "تعيين إلى (موظفين)" },
  "training.noEmployeesFound": { en: "No employees found. Add team members with \"Operations\" role first.", ar: "لا يوجد موظفون. أضف أعضاء فريق بدور \"عمليات\" أولاً." },
  "training.noLessonsEditYet": { en: "No lessons yet. Each lesson requires a video, PDF, or PowerPoint attachment.", ar: "لا توجد دروس بعد. كل درس يتطلب فيديو أو PDF أو PowerPoint مرفق." },
  "training.saveChanges": { en: "Save Changes", ar: "حفظ التغييرات" },
  "training.updateCourseDesc": { en: "Update the course details and lessons.", ar: "تحديث تفاصيل الدورة والدروس." },
  "training.deleteCourse": { en: "Delete Course", ar: "حذف الدورة" },
  "training.deleteCourseConfirm": { en: "Are you sure you want to delete this course? This action cannot be undone.", ar: "هل أنت متأكد من حذف هذه الدورة؟ لا يمكن التراجع عن هذا الإجراء." },
  "training.courseDeleted": { en: "Course Deleted", ar: "تم حذف الدورة" },
  "training.courseDeletedDesc": { en: "The training course has been removed from your hub.", ar: "تمت إزالة الدورة التدريبية من مركز التدريب." },
  "training.finishCourse": { en: "Finish Course", ar: "إنهاء الدورة" },
  "training.courseContent": { en: "Course Content", ar: "محتوى الدورة" },
  "training.pdfDocument": { en: "PDF Document", ar: "مستند PDF" },
  "training.powerpoint": { en: "PowerPoint", ar: "PowerPoint" },
  "training.video": { en: "Video", ar: "فيديو" },
  "training.textLesson": { en: "Text Lesson", ar: "درس نصي" },
  "training.downloadPowerPoint": { en: "Download PowerPoint", ar: "تحميل PowerPoint" },
  "training.pptxDownloadDesc": { en: "PowerPoint presentations can be downloaded for viewing", ar: "يمكن تحميل عروض PowerPoint للعرض" },
  "training.lessonXofY": { en: "Lesson", ar: "درس" },
  "training.of": { en: "of", ar: "من" },
  "training.coursePublished": { en: "Course Published", ar: "تم نشر الدورة" },
  "training.courseUpdated": { en: "Course Updated", ar: "تم تحديث الدورة" },
  "training.courseUpdatedDesc": { en: "Your changes have been saved.", ar: "تم حفظ تغييراتك." },
  "training.membersSelected": { en: "member(s) selected", ar: "عضو/أعضاء مختارين" },
  "training.movingToNext": { en: "Moving to the next lesson...", ar: "الانتقال إلى الدرس التالي..." },
  "training.congratsFinished": { en: "Congratulations! You've finished all lessons in this course.", ar: "تهانينا! لقد أكملت جميع الدروس في هذه الدورة." },
  "training.categoryAdded": { en: "Category Added", ar: "تمت إضافة الفئة" },
  "training.categoryRemoved": { en: "Category Removed", ar: "تمت إزالة الفئة" },
  "training.videoAttached": { en: "Video Attached", ar: "تم إرفاق الفيديو" },
  "training.pdfAttached": { en: "PDF Attached", ar: "تم إرفاق PDF" },
  "training.pptxAttached": { en: "PowerPoint Attached", ar: "تم إرفاق PowerPoint" },
  "training.categoryExists": { en: "Category already exists", ar: "الفئة موجودة بالفعل" },
  "training.pleaseSelectCategory": { en: "Please select a category", ar: "يرجى اختيار فئة" },
  "training.pleaseAddLesson": { en: "Please add at least one lesson", ar: "يرجى إضافة درس واحد على الأقل" },
  "training.allLessonsNeedAttachment": { en: "All lessons must have a video, PDF, or PowerPoint attached", ar: "يجب أن تحتوي جميع الدروس على فيديو أو PDF أو PowerPoint مرفق" },
  "training.missingAttachment": { en: "is missing an attachment.", ar: "ينقصه مرفق." },
  "training.pleaseEnterInstructor": { en: "Please enter an instructor name", ar: "يرجى إدخال اسم المدرب" },
  "training.pleaseEnterInstructorEmail": { en: "Please enter the instructor email", ar: "يرجى إدخال بريد المدرب" },
  "training.pleaseEnterDuration": { en: "Please enter the course duration", ar: "يرجى إدخال مدة الدورة" },
  "training.courseTitleRequired": { en: "Course title is required", ar: "عنوان الدورة مطلوب" },

  "team.title": { en: "Team", ar: "الفريق" },
  "team.management": { en: "Team Management", ar: "إدارة الفريق" },
  "team.members": { en: "Team Members", ar: "أعضاء الفريق" },
  "team.manageDescription": { en: "Manage users, roles, and permissions", ar: "إدارة المستخدمين والأدوار والصلاحيات" },
  "team.addMember": { en: "Add Member", ar: "إضافة عضو" },
  "team.addTeamMember": { en: "Add Team Member", ar: "إضافة عضو للفريق" },
  "team.editTeamMember": { en: "Edit Team Member", ar: "تعديل عضو الفريق" },
  "team.inviteMember": { en: "Invite Member", ar: "دعوة عضو" },
  "team.updateMember": { en: "Update Member", ar: "تحديث العضو" },
  "team.inviteDescription": { en: "Invite a new user to the SugarHive platform.", ar: "دعوة مستخدم جديد إلى منصة SugarHive." },
  "team.updateDescription": { en: "Update team member details below.", ar: "قم بتحديث تفاصيل عضو الفريق أدناه." },
  "team.name": { en: "Name", ar: "الاسم" },
  "team.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "team.email": { en: "Email", ar: "البريد الإلكتروني" },
  "team.emailAddress": { en: "Email Address", ar: "عنوان البريد الإلكتروني" },
  "team.role": { en: "Role", ar: "الدور" },
  "team.branch": { en: "Branch", ar: "الفرع" },
  "team.status": { en: "Status", ar: "الحالة" },
  "team.actions": { en: "Actions", ar: "الإجراءات" },
  "team.active": { en: "Active", ar: "نشط" },
  "team.inactive": { en: "Inactive", ar: "غير نشط" },
  "team.edit": { en: "Edit", ar: "تعديل" },
  "team.editDetails": { en: "Edit Details", ar: "تعديل التفاصيل" },
  "team.delete": { en: "Delete", ar: "حذف" },
  "team.filter": { en: "Filter", ar: "تصفية" },
  "team.filtersActive": { en: "Filters Active", ar: "التصفية نشطة" },
  "team.filterByRole": { en: "Filter by Role", ar: "تصفية حسب الدور" },
  "team.filterByBranch": { en: "Filter by Branch", ar: "تصفية حسب الفرع" },
  "team.allRoles": { en: "All Roles", ar: "جميع الأدوار" },
  "team.allBranches": { en: "All Branches", ar: "جميع الفروع" },
  "team.resetFilters": { en: "Reset Filters", ar: "إعادة تعيين التصفية" },
  "team.selectRole": { en: "Select role", ar: "اختر الدور" },
  "team.selectBranch": { en: "Select", ar: "اختر" },
  "team.selectRoleForInvitee": { en: "Select role for invitee", ar: "اختر الدور للمدعو" },
  "team.selectBranchInvite": { en: "Select branch", ar: "اختر الفرع" },
  "team.generateInvite": { en: "Generate Invite", ar: "إنشاء دعوة" },
  "team.generateInviteLink": { en: "Generate Invite Link", ar: "إنشاء رابط دعوة" },
  "team.generateInviteDescription": { en: "Create a one-time invite link for a new team member. They can use it to register themselves.", ar: "إنشاء رابط دعوة لمرة واحدة لعضو جديد في الفريق. يمكنهم استخدامه للتسجيل." },
  "team.generateLink": { en: "Generate Link", ar: "إنشاء الرابط" },
  "team.inviteLinkCreated": { en: "Invite Link Created!", ar: "تم إنشاء رابط الدعوة!" },
  "team.shareLinkMessage": { en: "Share this link with the new team member", ar: "شارك هذا الرابط مع عضو الفريق الجديد" },
  "team.inviteLink": { en: "Invite Link", ar: "رابط الدعوة" },
  "team.generateAnotherLink": { en: "Generate Another Link", ar: "إنشاء رابط آخر" },
  "team.inviteCode": { en: "Invite Code", ar: "رمز الدعوة" },
  "team.copyLink": { en: "Copy Link", ar: "نسخ الرابط" },
  "team.allMembers": { en: "All Members", ar: "جميع الأعضاء" },
  "team.search": { en: "Search team members...", ar: "البحث عن أعضاء الفريق..." },
  "team.noMembers": { en: "No team members found", ar: "لا يوجد أعضاء في الفريق" },
  "team.totalMembers": { en: "Total Members", ar: "إجمالي الأعضاء" },
  "team.showing": { en: "Showing", ar: "عرض" },
  "team.ofMembers": { en: "of", ar: "من" },
  "team.membersLabel": { en: "members", ar: "أعضاء" },
  "team.previous": { en: "Previous", ar: "السابق" },
  "team.next": { en: "Next", ar: "التالي" },
  "team.assignCourse": { en: "Assign Course", ar: "تعيين دورة" },
  "team.selectCourse": { en: "Select Course", ar: "اختر الدورة" },
  "team.chooseCourse": { en: "Choose a course...", ar: "اختر دورة..." },
  "team.alreadyAssigned": { en: "Already Assigned", ar: "معين مسبقاً" },
  "team.selectCourseToAssign": { en: "Select a course to assign to", ar: "اختر دورة لتعيينها إلى" },
  "team.thisMember": { en: "this member", ar: "هذا العضو" },
  "team.removeMember": { en: "Remove Member", ar: "إزالة العضو" },
  "team.removeConfirm": { en: "Are you sure you want to remove", ar: "هل أنت متأكد من إزالة" },
  "team.removeConfirmEnd": { en: "from the team? This action cannot be undone.", ar: "من الفريق؟ لا يمكن التراجع عن هذا الإجراء." },
  "team.remove": { en: "Remove", ar: "إزالة" },
  "team.deactivateUser": { en: "Deactivate User", ar: "إلغاء تنشيط المستخدم" },
  "team.activateUser": { en: "Activate User", ar: "تنشيط المستخدم" },
  "team.headquarters": { en: "Headquarters", ar: "المقر الرئيسي" },

  "branches.title": { en: "Branches", ar: "الفروع" },
  "branches.subtitle": { en: "Manage physical locations and branch operations", ar: "إدارة المواقع الفعلية وعمليات الفروع" },
  "branches.addBranch": { en: "Add Branch", ar: "إضافة فرع" },
  "branches.addNewBranch": { en: "Add New Branch", ar: "إضافة فرع جديد" },
  "branches.registerLocation": { en: "Register a new operational location.", ar: "تسجيل موقع تشغيلي جديد." },
  "branches.branchName": { en: "Branch Name", ar: "اسم الفرع" },
  "branches.location": { en: "Location", ar: "الموقع" },
  "branches.locationAddress": { en: "Location Address", ar: "عنوان الموقع" },
  "branches.manager": { en: "Manager", ar: "المدير" },
  "branches.branchManager": { en: "Branch Manager", ar: "مدير الفرع" },
  "branches.assignManager": { en: "Assign manager", ar: "تعيين مدير" },
  "branches.registerBranch": { en: "Register Branch", ar: "تسجيل الفرع" },
  "branches.branchRegistered": { en: "Branch Registered", ar: "تم تسجيل الفرع" },
  "branches.employees": { en: "Employees", ar: "الموظفين" },
  "branches.performance": { en: "Performance", ar: "الأداء" },
  "branches.viewDetails": { en: "View Details", ar: "عرض التفاصيل" },
  "branches.totalStaff": { en: "Total Staff", ar: "إجمالي الموظفين" },
  "branches.members": { en: "Members", ar: "أعضاء" },
  "branches.locationsTitle": { en: "Branches & Locations", ar: "الفروع والمواقع" },
  "branches.activeBranch": { en: "Active Branch", ar: "فرع نشط" },
  "branches.inactiveBranch": { en: "Inactive Branch", ar: "فرع غير نشط" },
  "branches.operationalPerformance": { en: "Operational Performance", ar: "الأداء التشغيلي" },
  "branches.complianceScore": { en: "Compliance Score", ar: "نسبة الامتثال" },
  "branches.totalChecklists": { en: "Total Checklists", ar: "إجمالي قوائم المهام" },
  "branches.completed": { en: "Completed", ar: "مكتمل" },
  "branches.staff": { en: "Staff", ar: "الموظفين" },
  "branches.branchChecklists": { en: "Branch Checklists", ar: "قوائم مهام الفرع" },
  "branches.allChecklistsAssigned": { en: "All checklists assigned to this branch", ar: "جميع قوائم المهام المعينة لهذا الفرع" },
  "branches.viewAll": { en: "View All", ar: "عرض الكل" },
  "branches.noChecklistsAssigned": { en: "No checklists assigned to this branch yet.", ar: "لا توجد قوائم مهام معينة لهذا الفرع بعد." },
  "branches.branchStaff": { en: "Branch Staff", ar: "موظفو الفرع" },
  "branches.teamMembers": { en: "team members", ar: "أعضاء الفريق" },
  "branches.addStaff": { en: "Add Staff", ar: "إضافة موظف" },
  "branches.addStaffTo": { en: "Add Staff to", ar: "إضافة موظف إلى" },
  "branches.addNewTeamMember": { en: "Add a new team member to this branch.", ar: "إضافة عضو فريق جديد لهذا الفرع." },
  "branches.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "branches.emailAddress": { en: "Email Address", ar: "البريد الإلكتروني" },
  "branches.selectRole": { en: "Select role", ar: "اختر الدور" },
  "branches.addToBranch": { en: "Add to Branch", ar: "إضافة للفرع" },
  "branches.noStaff": { en: "No staff assigned to this branch.", ar: "لا يوجد موظفون معينون لهذا الفرع." },
  "branches.staffAdded": { en: "Staff Added", ar: "تمت إضافة الموظف" },
  "branches.branchInfo": { en: "Branch Info", ar: "معلومات الفرع" },
  "branches.checklistDetails": { en: "Checklist Details", ar: "تفاصيل قائمة المهام" },
  "branches.detailedInfo": { en: "Detailed information for this checklist.", ar: "معلومات تفصيلية لقائمة المهام هذه." },
  "branches.branchAnalysis": { en: "Branch Analysis", ar: "تحليل الفروع" },
  "branches.crossLocationPerformance": { en: "Cross-location operational performance", ar: "الأداء التشغيلي عبر المواقع" },
  "branches.efficiencyScore": { en: "Efficiency Score by Location", ar: "نسبة الكفاءة حسب الموقع" },
  "branches.scoreByCompliance": { en: "Overall operational score based on checklist compliance", ar: "النتيجة التشغيلية الإجمالية بناءً على الامتثال لقوائم المهام" },
  "branches.activeStaff": { en: "Active Staff", ar: "الموظفون النشطون" },
  "branches.openIssues": { en: "Open Issues", ar: "المشاكل المفتوحة" },
  "branches.branchComparison": { en: "Branch Comparison", ar: "مقارنة الفروع" },
  "branches.details": { en: "Details", ar: "التفاصيل" },

  "settings.title": { en: "Settings", ar: "الإعدادات" },
  "settings.organization": { en: "Organization", ar: "المنظمة" },
  "settings.organizationSettings": { en: "Organization Settings", ar: "إعدادات المنظمة" },
  "settings.configureCompany": { en: "Configure your company structure and system preferences", ar: "تكوين هيكل شركتك وتفضيلات النظام" },
  "settings.saveChanges": { en: "Save Changes", ar: "حفظ التغييرات" },
  "settings.generalInfo": { en: "General Information", ar: "المعلومات العامة" },
  "settings.basicDetails": { en: "Basic details about your organization", ar: "التفاصيل الأساسية عن منظمتك" },
  "settings.companyName": { en: "Company Name", ar: "اسم الشركة" },
  "settings.industry": { en: "Industry", ar: "المجال" },
  "settings.supportEmail": { en: "Support Email", ar: "البريد الإلكتروني للدعم" },
  "settings.securityRoles": { en: "Security & Roles", ar: "الأمان والأدوار" },
  "settings.manageAccess": { en: "Manage how your team accesses the system", ar: "إدارة كيفية وصول فريقك للنظام" },
  "settings.twoFactor": { en: "Two-Factor Authentication", ar: "المصادقة الثنائية" },
  "settings.twoFactorDesc": { en: "Add an extra layer of security to user accounts", ar: "إضافة طبقة أمان إضافية لحسابات المستخدمين" },
  "settings.enabled": { en: "Enabled", ar: "مفعّل" },
  "settings.mobileAccess": { en: "Mobile Access Control", ar: "التحكم في الوصول عبر الجوال" },
  "settings.mobileAccessDesc": { en: "Restrict which devices can access the operations dashboard", ar: "تقييد الأجهزة التي يمكنها الوصول إلى لوحة العمليات" },
  "settings.configure": { en: "Configure", ar: "تكوين" },
  "settings.documents": { en: "Documents", ar: "المستندات" },
  "settings.downloadDocs": { en: "Download project documents", ar: "تحميل مستندات المشروع" },
  "settings.brdDocument": { en: "Business Requirements Document", ar: "وثيقة متطلبات العمل" },
  "settings.brdDescription": { en: "Complete BRD with all project specifications", ar: "وثيقة كاملة بجميع مواصفات المشروع" },
  "settings.userStoriesDocument": { en: "User Stories Document", ar: "وثيقة قصص المستخدمين" },
  "settings.userStoriesDescription": { en: "56 user stories across 10 epics", ar: "56 قصة مستخدم عبر 10 ملاحم" },
  "settings.quickLinks": { en: "Quick Links", ar: "روابط سريعة" },
  "settings.publicWebsite": { en: "Public Website", ar: "الموقع العام" },
  "settings.billing": { en: "Billing & Subscription", ar: "الفواتير والاشتراك" },
  "settings.globalNotifications": { en: "Global Notifications", ar: "الإشعارات العامة" },
  "settings.general": { en: "General", ar: "عام" },

  "inbox.title": { en: "Inbox", ar: "صندوق الوارد" },
  "inbox.notifications": { en: "Notifications", ar: "الإشعارات" },
  "inbox.markAllRead": { en: "Mark All Read", ar: "تحديد الكل كمقروء" },
  "inbox.markAllAsRead": { en: "Mark All as Read", ar: "تحديد الكل كمقروء" },
  "inbox.noNotifications": { en: "No notifications", ar: "لا توجد إشعارات" },
  "inbox.all": { en: "All", ar: "الكل" },
  "inbox.unread": { en: "Unread", ar: "غير مقروء" },
  "inbox.read": { en: "Read", ar: "مقروء" },
  "inbox.searchNotifications": { en: "Search notifications...", ar: "البحث في الإشعارات..." },
  "inbox.allNotifications": { en: "All Notifications", ar: "جميع الإشعارات" },
  "inbox.noNotificationsYet": { en: "No notifications yet", ar: "لا توجد إشعارات بعد" },
  "inbox.notificationsAppearHere": { en: "When checklists are published and assigned, notifications will appear here.", ar: "عند نشر وتعيين قوائم المهام، ستظهر الإشعارات هنا." },
  "inbox.selectNotification": { en: "Select a notification to view details", ar: "اختر إشعارًا لعرض التفاصيل" },
  "inbox.notification": { en: "notification", ar: "إشعار" },
  "inbox.notifications_count": { en: "notifications", ar: "إشعارات" },

  "reports.dailyPerformance": { en: "Daily Performance", ar: "الأداء اليومي" },
  "reports.dailyPerformanceReport": { en: "Daily Performance Report", ar: "تقرير الأداء اليومي" },
  "reports.todaysOverview": { en: "Today's Overview", ar: "نظرة عامة على اليوم" },
  "reports.operationalHealth": { en: "Snapshot of operational health for", ar: "لمحة عن صحة العمليات لـ" },
  "reports.liveAnalytics": { en: "Live Analytics", ar: "تحليلات مباشرة" },
  "reports.completionRate": { en: "Completion Rate", ar: "معدل الإنجاز" },
  "reports.avgResolutionTime": { en: "Avg. Resolution Time", ar: "متوسط وقت الحل" },
  "reports.operationalEfficiency": { en: "Operational Efficiency", ar: "الكفاءة التشغيلية" },
  "reports.activityTrend": { en: "Activity Trend", ar: "اتجاه النشاط" },
  "reports.checklistCompletions": { en: "Checklist completions throughout the day", ar: "إنجاز قوائم المهام خلال اليوم" },
  "reports.categoryBreakdown": { en: "Category Breakdown", ar: "التوزيع حسب الفئة" },
  "reports.performanceByType": { en: "Performance score by checklist type", ar: "نتيجة الأداء حسب نوع قائمة المهام" },
  "reports.completionRateTooltip": { en: "Percentage of assigned checklists and tasks successfully completed within the expected timeframe.", ar: "نسبة قوائم المهام والمهام المعينة التي تم إنجازها بنجاح ضمن الإطار الزمني المتوقع." },
  "reports.resolutionTimeTooltip": { en: "The average time taken from reporting an operational issue to its final resolution and sign-off.", ar: "متوسط الوقت المستغرق من الإبلاغ عن مشكلة تشغيلية إلى حلها النهائي والمصادقة عليه." },
  "reports.efficiencyTooltip": { en: "Combined score of resource utilization, task speed, and adherence to safety protocols across all branches.", ar: "النتيجة المجمعة لاستخدام الموارد وسرعة المهام والالتزام ببروتوكولات السلامة عبر جميع الفروع." },
  "reports.stable": { en: "Stable", ar: "مستقر" },
  "reports.branchComparison": { en: "Branch Comparison", ar: "مقارنة الفروع" },

  "login.title": { en: "Sign in to SugarHive", ar: "تسجيل الدخول إلى SugarHive" },
  "login.email": { en: "Email", ar: "البريد الإلكتروني" },
  "login.password": { en: "Password", ar: "كلمة المرور" },
  "login.signIn": { en: "Sign In", ar: "تسجيل الدخول" },
  "login.signInToDashboard": { en: "Sign in to your operations dashboard", ar: "تسجيل الدخول إلى لوحة العمليات" },
  "login.pleaseEnterBoth": { en: "Please enter both email and password", ar: "يرجى إدخال البريد الإلكتروني وكلمة المرور" },
  "login.welcomeBack": { en: "Welcome back!", ar: "مرحبًا بعودتك!" },
  "login.loggedInSuccess": { en: "You have been logged in successfully.", ar: "تم تسجيل الدخول بنجاح." },
  "login.demoAccounts": { en: "Demo Accounts", ar: "حسابات تجريبية" },
  "login.haveInvite": { en: "Have an invite code?", ar: "لديك رمز دعوة؟" },
  "login.registerHere": { en: "Register here", ar: "سجل هنا" },
  "login.loginFailed": { en: "Login failed", ar: "فشل تسجيل الدخول" },

  "register.title": { en: "Join SugarHive", ar: "انضم إلى SugarHive" },
  "register.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "register.email": { en: "Email", ar: "البريد الإلكتروني" },
  "register.password": { en: "Password", ar: "كلمة المرور" },
  "register.confirmPassword": { en: "Confirm Password", ar: "تأكيد كلمة المرور" },
  "register.createAccount": { en: "Create Account", ar: "إنشاء حساب" },
  "register.backToLogin": { en: "Back to Login", ar: "العودة لتسجيل الدخول" },
  "register.createYourAccount": { en: "Create your account to join the team", ar: "أنشئ حسابك للانضمام إلى الفريق" },
  "register.invitedAs": { en: "You've been invited as", ar: "تمت دعوتك كـ" },
  "register.at": { en: "at", ar: "في" },
  "register.fillAllFields": { en: "Please fill in all fields", ar: "يرجى ملء جميع الحقول" },
  "register.passwordsNoMatch": { en: "Passwords do not match", ar: "كلمات المرور غير متطابقة" },
  "register.passwordMinLength": { en: "Password must be at least 6 characters", ar: "كلمة المرور يجب أن تكون 6 أحرف على الأقل" },
  "register.welcomeToSugarHive": { en: "Welcome to SugarHive!", ar: "مرحبًا بك في SugarHive!" },
  "register.accountCreated": { en: "Your account has been created successfully.", ar: "تم إنشاء حسابك بنجاح." },
  "register.invalidInvite": { en: "Invalid Invite Link", ar: "رابط دعوة غير صالح" },
  "register.invalidInviteDesc": { en: "This invite link is invalid, expired, or has already been used. Please ask your administrator for a new invite.", ar: "رابط الدعوة هذا غير صالح أو منتهي الصلاحية أو تم استخدامه بالفعل. يرجى طلب دعوة جديدة من المسؤول." },
  "register.alreadyHaveAccount": { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
  "register.signIn": { en: "Sign in", ar: "تسجيل الدخول" },
  "register.registrationFailed": { en: "Registration failed", ar: "فشل التسجيل" },

  "notFound.title": { en: "404 Page Not Found", ar: "404 الصفحة غير موجودة" },
  "notFound.message": { en: "Did you forget to add the page to the router?", ar: "هل نسيت إضافة الصفحة إلى الراوتر؟" },

  "common.save": { en: "Save", ar: "حفظ" },
  "common.cancel": { en: "Cancel", ar: "إلغاء" },
  "common.delete": { en: "Delete", ar: "حذف" },
  "common.edit": { en: "Edit", ar: "تعديل" },
  "common.close": { en: "Close", ar: "إغلاق" },
  "common.confirm": { en: "Confirm", ar: "تأكيد" },
  "common.yes": { en: "Yes", ar: "نعم" },
  "common.no": { en: "No", ar: "لا" },
  "common.loading": { en: "Loading...", ar: "جار التحميل..." },
  "common.noData": { en: "No data available", ar: "لا توجد بيانات" },
  "common.daily": { en: "Daily", ar: "يومي" },
  "common.weekly": { en: "Weekly", ar: "أسبوعي" },
  "common.monthly": { en: "Monthly", ar: "شهري" },
  "common.all": { en: "All", ar: "الكل" },
  "common.or": { en: "or", ar: "أو" },
  "common.of": { en: "of", ar: "من" },
  "common.tasks": { en: "tasks", ar: "مهام" },
  "common.completed": { en: "completed", ar: "مكتمل" },
  "common.inProgress": { en: "in progress", ar: "قيد التنفيذ" },

  "status.completed": { en: "Completed", ar: "مكتمل" },
  "status.complete": { en: "Complete", ar: "مكتمل" },
  "status.partial": { en: "Partial", ar: "جزئي" },
  "status.incomplete": { en: "Incomplete", ar: "غير مكتمل" },
  "status.overdue": { en: "Overdue", ar: "متأخر" },
  "status.draft": { en: "Draft", ar: "مسودة" },
  "status.active": { en: "Active", ar: "نشط" },

  "confirm.deleteTitle": { en: "Confirm Delete", ar: "تأكيد الحذف" },
  "confirm.deleteMessage": { en: "Are you sure you want to delete this? This action cannot be undone.", ar: "هل أنت متأكد من الحذف؟ لا يمكن التراجع عن هذا الإجراء." },
  "confirm.unpublishTitle": { en: "Confirm Unpublish", ar: "تأكيد إلغاء النشر" },
  "confirm.unpublishMessage": { en: "This will revert the checklist to draft. All task progress will be reset.", ar: "سيتم إرجاع قائمة المهام إلى مسودة. سيتم إعادة تعيين جميع تقدم المهام." },

  "notification.newTrainingAssigned": { en: "New Training Assigned", ar: "تم تعيين تدريب جديد" },
  "notification.trainingAssignedMessage": { en: "You have been assigned the training course", ar: "تم تعيينك في دورة التدريب" },
  "notification.lessonsCount": { en: "lesson", ar: "درس" },
  "notification.lessonsCountPlural": { en: "lessons", ar: "دروس" },
  "notification.itHas": { en: "It has", ar: "تحتوي على" },
  "notification.newChecklistAssigned": { en: "New Checklist Assigned", ar: "تم تعيين قائمة مهام جديدة" },
  "notification.checklistAssignedMessage": { en: "You have been assigned to", ar: "تم تعيينك في" },
  "notification.branch": { en: "Branch", ar: "الفرع" },
  "inbox.operationsSystem": { en: "Operations System", ar: "نظام العمليات" },

  "log.completedChecklist": { en: "completed checklist", ar: "أكمل قائمة المهام" },
  "log.checklistOverdue": { en: "Checklist overdue", ar: "قائمة مهام متأخرة" },
  "log.assignedTo": { en: "assigned to", ar: "مكلف إلى" },
  "log.partiallyCompleted": { en: "partially completed checklist", ar: "أكمل جزئياً قائمة المهام" },
  "log.courseAssigned": { en: "Course assigned", ar: "تم تعيين الدورة" },
  "log.assignedToEmployees": { en: "assigned to", ar: "مكلف إلى" },
  "log.employee": { en: "employee", ar: "موظف" },
  "log.employees": { en: "employees", ar: "موظفين" },
  "log.courseCompleted": { en: "Course completed", ar: "اكتملت الدورة" },
  "log.allLessonsFinished": { en: "all lessons finished", ar: "جميع الدروس مكتملة" },
  "log.isActive": { en: "is active", ar: "نشط" },

  "language.toggle": { en: "العربية", ar: "English" },

  "time.justNow": { en: "Just now", ar: "الآن" },
  "time.minsAgo": { en: "min(s) ago", ar: "دقيقة/دقائق مضت" },
  "time.hrsAgo": { en: "h ago", ar: "ساعة/ساعات مضت" },
  "time.daysAgo": { en: "d ago", ar: "يوم/أيام مضت" },

  "placeholder.branchName": { en: "e.g. Medina North", ar: "مثال: المدينة شمال" },
  "placeholder.locationAddress": { en: "Street name, City (Optional)", ar: "اسم الشارع، المدينة (اختياري)" },
  "placeholder.fullName": { en: "e.g. Abdullah Jamil", ar: "مثال: عبدالله جميل" },
  "placeholder.email": { en: "email@sugarhive.com", ar: "email@sugarhive.com" },
  "placeholder.checklistTitle": { en: "e.g. Kitchen Closing Audit", ar: "مثال: تدقيق إغلاق المطبخ" },
  "placeholder.password": { en: "Enter your password", ar: "أدخل كلمة المرور" },
  "placeholder.loginEmail": { en: "you@sugarhive.com", ar: "you@sugarhive.com" },
  "placeholder.yourFullName": { en: "Your full name", ar: "اسمك الكامل" },
  "placeholder.registerEmail": { en: "you@example.com", ar: "you@example.com" },
  "placeholder.minChars": { en: "At least 6 characters", ar: "6 أحرف على الأقل" },
  "placeholder.reEnterPassword": { en: "Re-enter your password", ar: "أعد إدخال كلمة المرور" },
  "placeholder.courseTitle": { en: "e.g. Advanced Customer Service", ar: "مثال: خدمة عملاء متقدمة" },
  "placeholder.instructor": { en: "e.g. Ahmed Ali", ar: "مثال: أحمد علي" },
  "placeholder.instructorEmail": { en: "e.g. ahmed@sugarhive.com", ar: "مثال: ahmed@sugarhive.com" },
  "placeholder.duration": { en: "e.g. 2.5 hrs", ar: "مثال: 2.5 ساعة" },
  "placeholder.courseDescription": { en: "Explain what the learner will gain from this course...", ar: "اشرح ما سيكتسبه المتعلم من هذه الدورة..." },

  "toast.tasksAddedDesc": { en: "tasks added to the checklist.", ar: "مهام تمت إضافتها إلى قائمة المهام." },
  "toast.branchRegisteredDesc": { en: "has been successfully registered.", ar: "تم تسجيله بنجاح." },
  "toast.staffAddedDesc": { en: "has been added to", ar: "تمت إضافته إلى" },
  "toast.memberInvitedDesc": { en: "has been successfully invited.", ar: "تمت دعوته بنجاح." },
};

export const nameTranslations: Record<string, string> = {
  "Ahmed Admin": "أحمد أدمن",
  "Sara Ahmed": "سارة أحمد",
  "Mohammed Al-Otaibi": "محمد العتيبي",
  "Khalid Al-Shamri": "خالد الشمري",
  "Faisal Khalid": "فيصل خالد",
  "Noura Ali": "نورة علي",
  "Layla Hassan": "ليلى حسن",
  "Omar Fahad": "عمر فهد",
  "Reem Al-Dosari": "ريم الدوسري",
  "Youssef Nasser": "يوسف ناصر",
  "Huda Al-Qahtani": "هدى القحطاني",
  "Tariq Saleh": "طارق صالح",
  "Mona Ibrahim": "منى إبراهيم",
  "Ali Al-Harbi": "علي الحربي",
  "Fatimah Zayed": "فاطمة زايد",
  "Hassan Majed": "حسن ماجد",
};

export const roleTranslations: Record<string, string> = {
  "Super Admin": "المدير العام",
  "Branch Manager": "مدير الفرع",
  "Supervisor": "مشرف",
  "Operations": "العمليات",
  "Employee": "موظف",
};

export const branchTranslations: Record<string, string> = {
  "Headquarters": "المقر الرئيسي",
  "Riyadh Front": "الرياض فرونت",
  "Jeddah Main": "جدة الرئيسي",
  "Dammam Hub": "الدمام هب",
  "Makkah Center": "مكة سنتر",
  "All Branches": "جميع الفروع",
};

export const statusTranslations: Record<string, string> = {
  "Active": "نشط",
  "Inactive": "غير نشط",
};

export function translateName(name: string, language: Language): string {
  if (language === "ar" && nameTranslations[name]) return nameTranslations[name];
  return name;
}

export function translateRole(role: string, language: Language): string {
  if (language === "ar" && roleTranslations[role]) return roleTranslations[role];
  return role;
}

export function translateBranch(branch: string, language: Language): string {
  if (language === "ar" && branchTranslations[branch]) return branchTranslations[branch];
  return branch;
}

export function translateStatus(status: string, language: Language): string {
  if (language === "ar" && statusTranslations[status]) return statusTranslations[status];
  return status;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(LANG_KEY);
    return (saved === "ar" ? "ar" : "en") as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANG_KEY, lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, []);

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL: language === "ar" }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
